#!/bin/bash

my_name=`git config --get user.name`
my_email=`git config --get user.email`

start=0; 
while :; do
    top=`git shortlog -s | sort -r | head -1 | awk '{$1="";print $0}'`
    [[ "$top" =~ "$my_name" ]] && break;
    git shortlog -s | sort -r |\
        awk 'NR==1 || /"${my_name}"/{print $1 " " $2}' | tr "\n" " " |\
        awk '{print $1 - $3 " " $2}'|\
        if read num_author; then
            num=`echo $num_author | awk '{print $1}'`
            author_frg=`echo $num_author | awk '{print $2}'`
            count=`expr \( "$num" + 1\) /2 + $start`
            range="HEAD~${count}..HEAD"
            if [[ "$start" != "0" ]]; then
                range="${range}~${start}"
            fi
            git filter-branch -f --commit-fileter \
                'if [[ "$GIT_AUTHOR_NAME" =~ ^'"${author_frg}"']]; then
                    GIT_AUTHOR_NAME=""${my_name}""
                    GIT_AUTHOR_EMAIL=""${my_email}""
                    git commit-tree "$@";
                else
                    git commit-tree "$@"
                fi'
            "${range}";
        else
            break;
        fi
done
